### PR TITLE
Countdown timer

### PR DESCRIPTION
**Pull request by theokoles7**
## Overview
This PR will add the front end code for a countdown-timer as discussed in #349 

Connects #349 

### Demo
image

## Testing Instructions
- Create a board and verify that the timer is visible in the team header
- Default time of 5 minutes should be displayed
- Users can utilize the drop select menu to choose preset times of 10, 15, 30, and 45 minutes
- Once desired time has been selected, press the [green] play button, and the timer should begin counting down
- While the timer is in a running state, the user can click the [yellow] pause button which will halt the timer, but not reset it
- While the timer is paused, the user can once again click the play button and the timer should continue from the time that it left off from
- At any time after the timer has been started, the user can click the [red] clear button, which will cause the drop down menu to once again be displayed for the user to select another time
- When the timer runs down to zero, a dialogue box should appear stating such
- From the dialogue box, the user can then select "Okay!" which will simply close the modal, or they can select "One more minute" which will both reset the timer to one minute and automatically start the countdown without the user having to click play again

### CODE REVIEW

**Comment by LowBudgetMan** [comment]
Hey @theokoles7, I noticed a couple things on this PR. It looks like we had a couple linter errors but you seem to have taken care of that. Another thing I noticed when I pulled the code down is that when typing a 5 into the hours on the clock it seems to think it actually means 50? Could be worth taking a look at. Finally, we try to make sure all the code getting added to the code base is tested to make regressions much easier to notice and make sure our code does what we think it  does. I know you said you're not super familiar with Angular, so if you want I have time next Friday afternoon where we could pair on adding those tests if you want!

**Comment by theokoles7** [comment]
>Another thing I noticed when I pulled the code down is that when typing a 5 into the hours on the clock it seems to think it actually means 50? 

Right, I thought that I had fixed that. Apparently my solution wasn't as effective as I thought it was. I will continue trying to fix that.

>I know you said you're not super familiar with Angular, so if you want I have time next Friday afternoon where we could pair on adding those tests if you want!

Sure, I'd be up for doing that.

**Comment by LowBudgetMan** [comment]
Yeah, five minutes seems fine. We usually have retros for around an hour and let people add items for 10-15 minutes, but I think everyone's different. Five should be fine as a default I think.

And cool! Any preferred tools you use for pairing or voice?

**Comment by theokoles7** [comment]
@LowBudgetMan Discord? I've never used Discord for calls, but I think that's the best that I would have available on my system right now.

**Comment by LowBudgetMan** [comment]
Sent!

**Comment by LowBudgetMan** [comment]
@theokoles7 Quick question, just to jog my memory, would you find this change to be beneficial if we just added the timer for now and didn't hook up the websocket? We've been having some trouble with it recently and don't want to start to tackle adding more to it until we get #351 and the underlying problems solved.

**Comment by theokoles7** [comment]
> @theokoles7 Quick question, just to jog my memory, would you find this change to be beneficial if we just added the timer for now and didn't hook up the websocket? We've been having some trouble with it recently and don't want to start to tackle adding more to it until we get #351 and the underlying problems solved.

Right, that is why we were making this PR. You said that you wanted the front end code for now, and if need be, the retro session host could share their screen.

**Comment by LowBudgetMan** [comment]
@theokoles7 Okay, cool. I thought so but wanted to double-check!

**Comment by LowBudgetMan** [comment]
@theokoles7 

I'm having some FordLabs designers look at the Timer and see what they think about it. Couple of notes so far: 
* Disable inputs while timer is counting
* Would be cool if the play button turned into the pause button
* Left align the timer with the left-most column rather than it being next to the other action buttons
* Add some hover states and cursors for the buttons
* Have a way to clear the timer fields out

We don't have to have all of this done before we push the first version of the timer but some of it could be pretty easy to add. I'll add the Figma link to the repository description when they have it up.

Also, I've noticed on my local machine it's still taking in a huge number when I update the minutes count so I'm gonna poke a little more into that when I get some free time. I feel like the tests should cover it but it's not. Might be something on my end.

**Comment by theokoles7** [comment]
Sounds good, I'll stat working on that.

**Comment by LowBudgetMan** [comment]
With the React rewrite done, I'm going to close this PR and open a new one once I port over the Timer code to React. Let me know if you're interested in taking a look at that!

**Pull request closed without merging**
