### PR TITLE
Newest archive first

### PR DESCRIPTION
**Pull request by chiptopher**
## Overview
This will make it so that archived boards will be ordered to have the most recent board on top.

Connects #169 

## Testing Instructions
* Log into your board and add a set of thoughts.
* Archive the board
* Add another set of thoughts
* Archive the board

When you go to the list of archived boards, the first set of thoughts should appear in the second board from the top. The second set of thoughts should appear in the top board.

### CODE REVIEW

**Comment by chiptopher** [comment]
I decided to move the sorting from the frontend to the backend.

**Comment by Druage** [comment]
@chiptopher When I test this I still see the old archives before the new. I'm using Chrome.

**Comment by chiptopher** [comment]
@Druage Can you confirm the dates that the boards are coming back as? The repository gets the boards `OrderByDateCreatedDesc`. My guess is that because the dates are LocalDate's, and only save `yyyy-mm-dd`, two boards archived on the same day would come back in the order that they were created in (with the oldest ones first).

The following API test seems to confirm this:
```
    @Test
    public void getBoardsReturnsNewestBoardsFirstWhenTheyAreOnTheSameDay() throws Exception {
        Board oldBoard = Board.builder()
                .dateCreated(LocalDate.of(2018, 1, 1))
                .teamId(teamId)
                .thoughts(Collections.emptyList())
                .build();
        Board newBoard = Board.builder()
                .dateCreated(LocalDate.of(2018, 1, 1))
                .teamId(teamId)
                .thoughts(Collections.emptyList())
                .build();
        boardRepository.save(oldBoard);
        boardRepository.save(newBoard);

        mockMvc.perform(get("/api/team/"+ teamId + "/boards")
                .header("Authorization", getBearerAuthToken()))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].id", Matchers.is(newBoard.getId())))
                .andExpect(jsonPath("$[1].id", Matchers.is(oldBoard.getId())));
    }
```
When I set my computer's date to yesterday and archived the board, it comes last in the list.

Can you try to adjust your machine's date, try again, and let me know what happens.

**Comment by Druage** [comment]
@chiptopher I see what your saying and it does order them correctly when the dates or different.

**Pull request merged**
