### PR TITLE
Change ui port back to React default (3000)

### PR DESCRIPTION
**Pull request by Druage**
## Overview
Changes the frontend port back to the React default, which is port 3000. It doesn't have to be 4200 for any particular reason.

### CODE REVIEW

**Review by RandomAshes — CHANGES_REQUESTED** [review]
Please update the cypress.json as well

**Review by LowBudgetMan — CHANGES_REQUESTED** [review]
We should probably update the README with the new port as well.

**Review by LowBudgetMan — APPROVED** [review]
lgtm

**Review by RandomAshes — APPROVED** [review]
Looks good to me!

**Pull request merged**
