### PR TITLE
Adds mapping between action items and thoughts

### PR DESCRIPTION
**Pull request by Druage**
Signed-off-by: Patrick Saperstein <patricksaperstein@gmail.com>

Solves issue #185

### CODE REVIEW

**Comment by Druage** [comment]
Check out this resource https://hellokoding.com/jpa-many-to-many-relationship-mapping-example-with-spring-boot-maven-and-mysql/

**Comment by Druage** [comment]
The work is real.

image

image

**Comment by Druage** [comment]
Here are some designs that I have been toying with. Any suggestions? 
untitled

**Comment by abarna10** [comment]
I vote for the top middle image and if clicked the top right image appears.

**Comment by Druage** [comment]
After tallying the votes the design that one is the first one on the far left. Hurray!!! The results were a 4 - 1 spread.

Here is what I currently have actually in code and working.

image

image

image

image

**Pull request closed without merging**
